---
output:
  html_document:
    toc: false
params:
  project_directory: "/Users/isaac/Dropbox/S2P Datasets Shared Folder/MLTC_MMC_NH_data/"
  use_local_data: FALSE
---

<style>
.button_download {
  font-size: 16px;
  font-family: "Arial";
  color: black;
  background-color: #C7C9D8;
}
</style>

```{r setup_options, include=FALSE}
knitr::opts_chunk$set(eval = TRUE, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE, error = TRUE, fig.width = 12, fig.height = 8, cache = FALSE)
```

```{r setup_libraries, include=FALSE}
library(tidyverse)
library(furrr)
library(scales)
library(gt)
library(downloadthis)
data_dir <- params$project_directory
```

```{r isaac_step2_graph_theme, include=FALSE}
isaac_step2_graph_theme <- theme(plot.title.position = "plot",
                                 plot.title = element_text(face = "bold"),
                                 legend.position = "top",
                                 strip.text = element_text(color = "black"),
                                 legend.title = element_text(face = "bold",hjust = 0.5),
                                 axis.title.y = element_text(face = "bold",angle = 90),
                                 axis.title.x = element_text(face = "bold"))
```

```{r setup_medicaid_enrollment_data_ingestion, include=FALSE}
if(params$use_local_data == FALSE){
  # https://health.data.ny.gov/Health/Medicaid-Program-Enrollment-by-Month-Beginning-200/m4hz-kzn3/about_data
  nys_medicaid <- read_csv("https://health.data.ny.gov/api/views/m4hz-kzn3/rows.csv?accessType=DOWNLOAD") %>% janitor::clean_names()
  
  write_csv(nys_medicaid,paste0(data_dir,'mmc_mltc/data/Medicaid-Program-Enrollment-by-Month-Beginning-2009.csv'))
} else{
  nys_medicaid <- read_csv(paste0(data_dir,'mmc_mltc/data/Medicaid-Program-Enrollment-by-Month-Beginning-2009.csv'))
}
```

```{r setup_harp_analysis, include=FALSE}
harp_analysis <- nys_medicaid %>% 
  filter(managed_care_vs_fee_for_service == "MMC",
         plan_type == "HARP") %>% 
  mutate(month_year = paste(eligibility_year,eligibility_month,"01",sep = "-") %>% as.Date(),
         year = paste(eligibility_year,"01","01",sep = "-") %>% as.Date())

harp_trends <- harp_analysis %>%
  group_by(month_year,plan_type) %>%
  summarise(enrolled = sum(number_of_recipients)) %>%
  ungroup() %>%
  bind_rows(harp_analysis %>%
              group_by(month_year) %>%
              summarise(enrolled = sum(number_of_recipients)) %>%
              ungroup() %>%
              mutate(plan_type = "Total")) %>%
  ggplot(aes(x = month_year,
             y = enrolled)) +
  geom_line() +
  geom_point(size = 1.25,
             alpha = 0.85) +
  labs(title = "Statewide HARP Enrollment by Month",
       subtitle = paste0("New York State (",
                         format(min(harp_analysis$month_year),"%b %Y"),
                         " to ",
                         format(max(harp_analysis$month_year),"%b %Y"),
                         ")"),
       x = "",
       y = "Number of Enrollees\n",
       caption = paste0("Data Source: Health Data NY\nData as of: ",format(Sys.Date(),"%B %d, %Y"))) +
  scale_x_date(breaks = breaks_pretty(n = 8)) +
  scale_y_continuous(breaks = breaks_pretty(n = 8),
                     labels = comma_format(accuracy = 1),
                     limits = c(0,NA)) +
  theme_light(base_size = 16) +
  isaac_step2_graph_theme

harp_trends_table_data <- harp_analysis %>% 
  group_by(year) %>% 
  summarise(months_reported = eligibility_month %>% unique() %>% length(),
            enrollee_months = sum(number_of_recipients)) %>% 
  ungroup() %>% 
  left_join(harp_analysis %>% 
  group_by(year,eligibility_month) %>% 
  summarise(enrollee_months = sum(number_of_recipients)) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  summarise(average_monthly_number_or_enrollees = mean(enrollee_months)) %>% 
  ungroup(),
  by = "year") %>% 
  arrange(desc(year))


harp_trends_table <- harp_trends_table_data %>% 
  gt() %>% 
  tab_header(title = md("**HARP Enrollee Months, by Year**"),
             subtitle = paste0("New York State (",
                               format(min(harp_analysis$month_year),"%b %Y"),
                               " to ",
                               format(max(harp_analysis$month_year),"%b %Y"),
                               ")")) %>% 
  fmt_date(columns = year,
           date_style = "year") %>% 
  fmt_integer(is.numeric) %>% 
  cols_label(year = "Year",
             months_reported = "Months Reported",
             enrollee_months = "HARP Enrollee Months",
             average_monthly_number_or_enrollees = "Average Monthly Number of Enrollees") %>% 
  cols_align(align = "left", columns = year) %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_column_labels()) %>% 
  tab_source_note(source_note = md("**Data Source:** Health Data NY")) %>% 
  tab_source_note(source_note = md(paste0("**Data as of:** ",format(Sys.Date(),"%B %d, %Y")))) %>% 
  # cols_width(year ~ px(175),
  #            all_of(c("Beds","Available")) ~ px(150)) %>% 
  tab_options(table.font.size = px(10),
              table.font.names = "Helvetica",
              data_row.padding = px(2))
```

<br>

```{r harp_trends_table}
harp_trends_table %>% 
  tab_source_note(
    harp_trends_table_data %>%
      download_this(
        output_name = paste0("harp_enrollment__",str_replace_all(Sys.Date(),"-","_")),
        output_extension = ".xlsx",
        button_label = "Download Excel Workbook",
        button_type = "default",
        class = "button_download"
      )
  )
```

**Data Source:** [Health Data NY](https://health.data.ny.gov/Health/Medicaid-Program-Enrollment-by-Month-Beginning-200/m4hz-kzn3/about_data)

<br>

```{r harp_trends}
harp_trends
```

**Data Source:** [Health Data NY](https://health.data.ny.gov/Health/Medicaid-Program-Enrollment-by-Month-Beginning-200/m4hz-kzn3/about_data)

<br>
